### ISSUE TITLE
oc_struct.go:Device does not implement ygot.ValidatedGoStruct interface

### ISSUE THREAD

**Issue by samribeiro** [google/gnxi#2]
--- FAIL: TestCapabilities (0.00s)
	target_test.go:47: error in creating target: root node is not a ygot.ValidatedGoStruct

**Comment by samribeiro** [comment]
gnxi/utils/target/gnmi/model_data/oc_struct/oc_struct.go:Device does not implement ygo.ValidatedGoStruct interface

**Comment by larryleguo** [comment]
This is due to the changes of ygot library. The go struct code needs to be regenerated.

**Comment by samribeiro** [comment]
still see the issue with latest merge.

**Comment by larryleguo** [comment]
generated go file updated.
