### ISSUE TITLE
gnoi_os.go install should have version as optional input

### ISSUE THREAD

**Issue by Reshad-Rahman** [google/gnxi#203]
Right now if version isn't provided the client exits:
F0812 14:45:49.286570   16552 gnoi_os.go:80] No version provided. Provide one with -version
Code is here:
https://github.com/google/gnxi/blob/master/gnoi_os/gnoi_os.go#L80

But the version is optional:
https://github.com/openconfig/gnoi/blob/master/os/os.proto#L139

**Comment by samribeiro** [comment]
Indeed, version should not be required for Install. Thanks for catching this.
