### ISSUE TITLE
Reset start rpc arguments need to be switched around.

### ISSUE THREAD

**Issue by alisharif2** [google/gnxi#265]
https://github.com/google/gnxi/blob/4b504ef806a7f4f65d2d8b4ff14aad5edbd2c889/gnoi_reset/gnoi_reset.go#L58

The zero fill option is being passed as the factory OS option and vice versa.

https://github.com/google/gnxi/blob/4b504ef806a7f4f65d2d8b4ff14aad5edbd2c889/gnoi/reset/client.go#L49

**Comment by samribeiro** [comment]
thanks!
