### ISSUE TITLE
which version of openconfig yang models

### ISSUE THREAD

**Issue by vainyksi** [google/gnxi#29]
Hi,
which version of openconfig yang models do you actually support or is intended to support?

There are kind of old version values for openconfig yang models in [gnxi/gnmi/modeldata/modeldata.go](https://github.com/google/gnxi/blob/master/gnmi/modeldata/modeldata.go). But it looks that model was actually generated from the current master of openconfig repository.

So, are the version values in gnxi/gnmi/modeldata/modeldata.go wrong?

**Comment by samribeiro** [comment]
Hi Michael, the focus is to have a functional reference implementation of gNMI and gNOI. For gNMI the server was built with some example OpenConfig models. The models used are only relevant to support and help validate the gNMI implementation.

For specific implementations, models and versions should be specifically selected. So to answer your question, there is really no right or wrong selection of models & version in this implementation. At least not yet.

**Comment by vainyksi** [comment]
Hi Sam,
aha, thank you for clarification.
