### ISSUE TITLE
Wrong usage of defer

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/gnxi#76]
The `defer statement` must be placed after the error check. Otherwise `listen` may be nil.
https://github.com/google/gnxi/blob/c14ccdb08c24e65e80106585d98bb07a40d65c30/gnoi_target/gnoi_target.go#L43-L47

**Comment by sergeysergeevru** [comment]
It should not be a problem. If log.Fatal happened defer part will not be executed.

**Comment by QiAnXinCodeSafe** [comment]
Yes, you are right. However, it is best to place the defer statement after the error check.
